name: Scheduled Tender Crawler

on:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC
  workflow_dispatch:        # Allows manual triggering

jobs:
  crawl-and-notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Set up Chrome and ChromeDriver
        uses: browser-actions/setup-chrome@latest
        with:
          chrome-version: stable
      
      - name: Run crawler script
        run: python main.py
      
      - name: Commit and push CSV if changed
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add output/*.csv
          git diff-index --quiet HEAD || git commit -m "Update tender CSV file - $(date)"
          git push origin master
      
      - name: Set date for filename
        id: date
        run: echo "date=$(date +'%Y%m%d')" >> $GITHUB_OUTPUT
      
      - name: Read WeChat formatted output
        id: wechat_message
        run: |
          if [ -f "output/tender_info_${{ steps.date.outputs.date }}.txt" ]; then
            echo "message=$(cat output/tender_info_${{ steps.date.outputs.date }}.txt | sed 's/\"/\\\"/g' | sed 's/\n/\\n/g')" >> $GITHUB_OUTPUT
          else
            echo "message=未找到博物馆相关的招标信息。" >> $GITHUB_OUTPUT
          fi
      
      - name: Send notification to WeChat Work
        if: success()
        run: |
          curl -X POST ${{ secrets.WECHAT_WEBHOOK_URL }} \
            -H "Content-Type: application/json" \
            -d "{\"msgtype\": \"text\", \"text\": {\"content\": \"${{ steps.wechat_message.outputs.message }}\"}}"
